language: python

addons:
  apt:
    packages:
      - libbz2-dev 
      - zlib1g-dev
      - libncurses5-dev
      - liblzma-dev
      - libncursesw5-dev
      - libcurl4-openssl-dev
      - gcc

before_install:
    - "export PATH=$PWD/.travis:$PWD/bin:$PATH"
    - "mkdir -p deps && cd deps && source install_deps.sh && cd .."
    - "pwd"
    - "echo $HOME"
    - "echo $PATH"
    - "find deps -executable -type f"

python:
  - "3.6"

install:
  - pip install -r src/requirements.txt

script:
  - cd src; bash run_tests.sh -cl 
