---
title: "plot examples"
author: "Kent Riemondy RBI"
date: "7/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
source("../../R/constants.R")
source("../../R/viz.R")
```

## Plot structures with VARNA

```{r}
m_files <- dir("~/Projects/rnastruct/results/2019-07-11_example_validation_structures/wt_map/", pattern = ".map", full.names = T)

m_dat <- purrr::map(m_files, read_map)
names(m_dat) <- basename(m_files) %>% str_remove("_coverage.map")
m_dat <- m_dat %>% 
  imap(., ~select(.x, react, nuc) %>%
         mutate(id = .y)) %>% 
  bind_rows() 

ss <- kentr::read_fasta("ss.fasta")

ss <- split(ss, ss$name) %>% map(~pull(.x, seq))

a <- split(m_dat, m_dat$id) %>% 
  map(~list(paste0(.x$nuc, collapse = ""),
           .x$react))
                               
dat <- imap(a, ~c(.x, ss[[.y]]))

outdir <- "wt_structures_binned"
dir.create(outdir)

for(i in seq_along(dat)){
  plot_secondary_structure_binned(seq = dat[[i]][[1]], 
                           ss = dat[[i]][[3]], 
                           color_by = dat[[i]][[2]],
                           outpath = file.path(
                             outdir,
                             paste0(names(dat[i]), "_wt_depth50.png")))
}
```




```{r}
m_files <- dir("~/Projects/rnastruct/results/2019-07-11_example_validation_structures/c4_map/", pattern = ".map", full.names = T)

m_dat <- purrr::map(m_files, read_map)
names(m_dat) <- basename(m_files) %>% str_remove("_coverage.map")
m_dat <- m_dat %>% 
  imap(., ~select(.x, react, nuc) %>%
         mutate(id = .y)) %>% 
  bind_rows() 

ss <- kentr::read_fasta("ss.fasta")

ss <- split(ss, ss$name) %>% map(~pull(.x, seq))

a <- split(m_dat, m_dat$id) %>% 
  map(~list(paste0(.x$nuc, collapse = ""),
           .x$react))
                               
dat <- imap(a, ~c(.x, ss[[.y]]))

outdir <- "c4_structures"
dir.create(outdir)

for(i in seq_along(dat)){
  plot_secondary_structure(seq = dat[[i]][[1]], 
                           ss = dat[[i]][[3]], 
                           color_by = dat[[i]][[2]],
                           outpath = file.path(
                             outdir,
                             paste0(names(dat[i]), "_c4_depth50.png")))
}
```


```{r}
m_files <- dir("~/Projects/rnastruct/results/2019-07-11_example_validation_structures/rRNA/wt_map/", pattern = ".map", full.names = T)

m_dat <- purrr::map(m_files, read_map)
names(m_dat) <- basename(m_files) %>% str_remove("_coverage.map")
m_dat <- m_dat %>% 
  imap(., ~select(.x, react, nuc) %>%
         mutate(id = .y)) %>% 
  bind_rows() 

ss <- kentr::read_fasta("rRNA/18sRNA_ss.fasta")
# use for 501 nt 
ss$seq <- str_split(ss$seq, "")[[1]][1:501] %>% paste0(. ,collapse="")
ss <- split(ss, ss$name) %>% map(~pull(.x, seq))

a <- split(m_dat, m_dat$id) %>% 
  map(~list(paste0(.x$nuc, collapse = ""),
           .x$react))
                               
dat <- imap(a, ~c(.x, ss[[.y]]))

outdir <- "rRNA/wt_structures"
dir.create(outdir)

for(i in seq_along(dat[1])){
  plot_secondary_structure(seq = dat[[i]][[1]], 
                           ss = dat[[i]][[3]], 
                           color_by = dat[[i]][[2]],
                           outpath = file.path(
                             outdir,
                             paste0(names(dat[i]), "_wt_depth1000.png")))
}


ref <- kentr::read_fasta("rRNA/18sRNA_ss.fasta")
wt_with_dms <- read_db("rRNA/wt_map/18s_full_coverage_with_dms.db")

wt_no_dms <- read_db("rRNA/wt_map/18s_full_coverage_without_dms.db")

calc_ss_similarity(wt_no_dms$ss, ref$seq, wt_no_dms$seq)
calc_ss_similarity(wt_with_dms$ss, ref$seq, wt_with_dms$seq)


## C4 mutant 

m_files <- dir("~/Projects/rnastruct/results/2019-07-11_example_validation_structures/rRNA/c4_map/", pattern = ".map", full.names = T)

m_dat <- purrr::map(m_files, read_map)
names(m_dat) <- basename(m_files) %>% str_remove("_coverage.map")
m_dat <- m_dat %>% 
  imap(., ~select(.x, react, nuc) %>%
         mutate(id = .y)) %>% 
  bind_rows() 

ss <- kentr::read_fasta("rRNA/18sRNA_ss.fasta")
# use for 501 nt 
ss$seq <- str_split(ss$seq, "")[[1]][1:501] %>% paste0(. ,collapse="")
ss <- split(ss, ss$name) %>% map(~pull(.x, seq))

a <- split(m_dat, m_dat$id) %>% 
  map(~list(paste0(.x$nuc, collapse = ""),
           .x$react))
                               
dat <- imap(a, ~c(.x, ss[[.y]]))

outdir <- "rRNA/c4_structures"
dir.create(outdir)

for(i in seq_along(dat[1])){
  plot_secondary_structure(seq = dat[[i]][[1]], 
                           ss = dat[[i]][[3]], 
                           color_by = dat[[i]][[2]],
                           outpath = file.path(
                             outdir,
                             paste0(names(dat[i]), "_c4_depth1000.png")))
}


```

