# config for RNA-Seq snakemake pipeline #
 
DATA:
  '/vol3/home/riemondy/Projects/rnastruct'

GENOME_DIR:
  "/vol2/home/ruifu/databases/star/gencode_GRCh38/"

GENOME_FA:
  "/vol3/home/riemondy/Projects/rnastruct/dbases/genome_plus_rrna.fa"

TRANSCRIPTS:
  "/vol3/home/riemondy/Projects/shared_dbases/annotation/gencode.v26.primary_assembly.annotation.gtf"

SAMPLES:
  - TS-C4-InVivo-DMS-Weeks_S35
  - TS-C4-UT-Weeks_S34
  - TS-E11-InVivo-DMS-Weeks_S37
  - TS-E11-UT-Weeks_S36
  - TS-WT-InVivo-DMS-Weeks_S33
  - TS-WT-UT-Weeks_S32
