---
title: "Structure score validation"
author: "Kent Riemondy RBI"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(txcompare)
library(valr)
source(here::here("R/constants.R"))
```


## Compare structure scores to rnastructurome data


```{r bws}
fwd_zscore_file <- "../../hub/hg19/rnastructurome/zscore/all_chr_forward_zscore_hg19.bw"
rev_zscore_file <- "../../hub/hg19/rnastructurome/zscore/all_chr_reverse_zscore_hg19.bw"
```


```{r ss_files}
wt_rep1 <- "../../data/enzymatic_data_july2019/struct_score/norm_coverage/WT/single_files/WT.tsv.gz"

wt_rep2 <- "../../data/enzymatic_data_aug2019/wt_rep2/struct_score/norm_coverage/WT/single_files/WT.tsv.gz"

wt_rep3 <-  "../../data/enzymatic_data_aug2019/wt_rep3/struct_score/norm_coverage/WT/single_files/WT.tsv.gz"

slow_rep1 <- "../../data/enzymatic_data_july2019/struct_score/norm_coverage/Slow/single_files/Slow.tsv.gz"
```


```{r chroms_to_examine}

chroms_to_check <- c(
  paste0("chr", rep(1:22)),
"chrX",
"chrY",
"chrM"
)

comp_rnastructurome_and_ss <- function(chrom_to_test = chroms_to_check[20], 
                                       ss_file = rep2,
                                       fwd_bw = fwd_zscore_file,
                                       rev_bw = rev_zscore_file,
                                       min_combined_reads = 50){
  message("working on chromosome ", chrom_to_test)
  ss_scores <- read_tabix(ss_file, region = chrom_to_test) %>% 
    dplyr::rename(strand = X11,
                  chrom = X1,
                  start = X2, 
                  end = X3,
                  structure_score = X10) %>% 
    filter((X5 + X6) > min_combined_reads)
  
  fwd_scores <- filter(ss_scores, strand == "+")
  rev_scores <- filter(ss_scores, strand == "-")
  
  fwd_zscores <- read_bw(fwd_bw, chrom = chrom_to_test)
  rev_zscores <- read_bw(rev_bw, chrom = chrom_to_test)
  
  fwd_summary <- bed_map(fwd_zscores, 
                         fwd_scores,
                         avg_ss = mean(structure_score, 
                                       na.rm = TRUE)) %>% 
    filter(!is.na(avg_ss))
  
  p <- ggplot(fwd_summary, aes(avg_ss, coverage)) + 
    geom_point() +
    geom_density_2d() 
  p
  return(p)
}
  
p <- comp_rnastructurome_and_ss(ss_file = slow_rep1, chrom_to_test = chroms_to_check[1])
  

  
plts <- imap(lst(wt_rep1,
                 wt_rep2,
                 wt_rep3,
                 slow_rep1), 
             ~comp_rnastructurome_and_ss(ss_file = .x, 
                                         chrom_to_test = chroms_to_check[1]) +
               labs(title = .y)
)
plts_final <- map(plts, 
                  ~.x + labs(x = "Mean Structure Score", 
                             y = "RnaStructuromeDb Z-score"))

plt <- cowplot::plot_grid(plotlist = plts_final, nrow = 2, ncol = 2)

plt

save_plot("rnastructuromedb_zscore_v_structure_score_chr1.pdf", plt, 
          nrow = 2, 
          ncol = 2,
          base_asp = 1.2)
```


Doesn't appear to be any correlation at all...
