
RAW_DATA: "../../data/enzymatic_data/"
DATA: "norm_data"
SAMPLES: 
    - "slow_mut"
    - "wild_type"

CHROMSIZES: "../chroms.txt"

CHROMS:
    - chr1
    - chr10
    - chr11
    - chr12
    - chr13
    - chr14
    - chr15
    - chr16
    - chr17
    - chr18
    - chr19
    - chr2
    - chr20
    - chr21
    - chr22
    - chr3
    - chr4
    - chr5
    - chr6
    - chr7
    - chr8
    - chr9
    - chrX
    - chrY
