---
title: "rRNA visualization"
author: "Kent Riemondy RBI"
date: "3/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(cache = TRUE)
```

```{r libs}
source("../../R/constants.R")
```

```{r varna_location}
Sys.setenv(VARNA = "/Users/kriemo/Downloads/VARNAv3-93.jar")
```
## Goals

1) Parse bedgraphs to extract out 18rRNA coverage. 

2) Convert reactivities to coordinates compatible with 18sRNA fasta

3) Overlay reactivity on 18sRNA secondary structure

```{r rrna_coords}
rrna_18s <- trbl_interval(
  ~chrom, ~start, ~end,
  "gi|555853|gb|U13369.1|HSU13369", 3657  - 1, 5527
)
```


```{r test_data}
bg <- read_bedgraph("test_bgs/TS-WT-InVivo-DMS-Weeks_S33_rRNA_pos_mismatches.bedgraph.gz")
rrna_coverage <- bed_intersect(bg, rrna_18s, suffix = c("", ".y")) %>% 
  select(-contains(".y"))

rrna_positions <- rrna_coverage %>% 
  mutate(pos = start + 1 - 3656,
         pos = as.integer(pos)) %>% 
  filter(pos > 0,
         pos <= (5527  - 3657))

all_positions <- data_frame(
  pos = seq(1, 5527  - 3657)
)

## indicate which nucleotides are reactive (> 0.01 reactivity)
all_rrna_reactivity <- left_join(all_positions, 
                                 rrna_positions, by = "pos") %>% 
  select(pos, value) %>% 
  mutate(value = ifelse(is.na(value) | value < 0.003, 
                        0,
                        1)) 
rrna_reactivity <- pull(all_rrna_reactivity, value) %>% 
  .[1:450] %>% 
  str_c(., collapse = ";")
```

```{r 18sRNA_structure_args}
rrna <- read_lines(file.path(docs_dir, "18sRNA_test.txt"))
rrna_seq <- rrna[2] %>% str_sub(., 1, 450)
rrna_struct <- rrna[3] %>% str_sub(., 1, 450)
Sys.setenv(SEQ = rrna_seq)
Sys.setenv(STRUCT = rrna_struct)
Sys.setenv(REACT = rrna_reactivity)
```
  
```{bash}
java \
  -cp $VARNA fr.orsay.lri.varna.applications.VARNAcmd \
  -sequenceDBN $SEQ \
  -structureDBN $STRUCT \
  -colorMap $REACT \
  -zoom 1 \
  -resolution "5.0" \
  -algorithm naview \
  -o "out.jpeg"
```
